typography_spectrum: 0.8952738
color:
  saturation: 0.2491453
  brandStrength: 1
  rhythmicContrast: 0.07360394
  brandColors:
    - '#C3DFE0'
    - '#8A8A8A'
    - '#353334'
    - '#697173'
    - '#ACB8B9'
  lightness: 0.7870788
layout_spectrum: 0.9543501
author:
  name: Michael Leighfield
  email: michaelleighfield@gmail.com
name: Mike Leighfield
navigation:
  - name: Event Photography
    id: ff945d2c-4e5e-44e8-bf70-2d090a2862c6
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Leighfield Photography
