typography_spectrum: 0.8952738
color:
  saturation: 0.2491453
  brandStrength: 1
  rhythmicContrast: 0.07360394
  brandColors:
    - '#C3DFE0'
    - '#8A8A8A'
    - '#353334'
    - '#697173'
    - '#ACB8B9'
  lightness: 0.7870788
layout_spectrum: 0.9543501
author:
  name: Michael Leighfield
  email: michaelleighfield@gmail.com
name: Mike Leighfield
navigation:
  - name: Event
    id: ff945d2c-4e5e-44e8-bf70-2d090a2862c6
    type: content
  - name: Portraiture
    id: 78b53923-5b31-4e40-864c-23f5c2d4f446
    type: content
  - name: Landscape
    id: d1876113-5977-4c62-aa1a-7c405bf6488c
    type: content
  - name: Product
    id: a0bdfba9-4cb7-45ce-9a29-cc95c9d03f0d
    type: content
  - name: Art Series
    id: 67d82468-01e8-4c3c-87c0-d7fea5a0c366
    type: content
  - name: Catching Up With Carol
    id: cb8afb4b-db0b-483c-a650-ab16cb62c23a
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Leighfield Photography
