layout_spectrum: 0
typography_spectrum: 0.8952738
color:
  saturation: 0.2491453
  lightness: 0.7870788
  brandStrength: 1
  brandColors:
    - '#C3DFE0'
    - '#8A8A8A'
    - '#353334'
    - '#697173'
    - '#ACB8B9'
  rhythmicContrast: 0.07360394
name: MikeLeighfield
